### ISSUE TITLE
I only use Acorn in Sage 10. Can I use this package in an environment where wp acorn is not available?

### ISSUE THREAD

**Issue by Hansanghyeon** [generoi/sage-woocommerce#25]
I have set up WordPress in a Docker environment. I am using the roots/sage theme for WordPress, and I have utilized Composer for the theme. I previously installed `roots/acorn` in the theme with the command `composer require roots/acorn`. Subsequently, I installed the `generoi/sage-woocommerce` package in the theme folder using composer require.

However, I am unable to use the wp acorn command as outlined in the README.md guide.

I did not install WordPress with Composer.

I'm unsure of what to do. Is there a solution?

**Comment by oxyc** [comment]
This command  doesnt work?

`wp acorn package:discover`

Any output? I actually haven’t tried that in quite some time and not sure what the acorn-way is currently. I can try and reproduce next week but I might be too slow to get back to you.

Another option is https://discourse.roots.io/t/woocommerce-integration-with-generoi-sage-woocommerce/24634/2

Yet another way (which is what I do) is use an AggregateServiceProvider instead of the default SageServiceProvider:

```php
<?php

namespace App\Providers;

use Illuminate\Support\AggregateServiceProvider;

class ThemeServiceProvider extends AggregateServiceProvider
{
    protected $providers = [
        \App\Providers\BlockPatternServiceProvider::class,
        \App\Providers\BlockServiceProvider::class,
        \App\Providers\ComponentServiceProvider::class,
        \App\Providers\SageServiceProvider::class,
        \App\Providers\PerformanceServiceProvider::class,
        \App\Providers\AsyncLoaderServiceProvider::class,
        \App\Providers\SmartCropServiceProvider::class,
        \App\Providers\FacetWpServiceProvider::class,
        \App\Tulospalvelu\Providers\TulospalveluServiceProvider::class,
        \Spatie\GoogleFonts\GoogleFontsServiceProvider::class,
        \Genero\Sage\CacheTags\CacheTagsServiceProvider::class,
    ];
}
```

**Comment by Hansanghyeon** [comment]
Thank you, and I was able to resolve it thanks to your reply.
