### ISSUE TITLE
Radicle 1.3.2 - acorn vendor:publish

### ISSUE THREAD

**Issue by davideprevosto** [generoi/sage-woocommerce#28]
Hello, running the following command, on a Radicle 1.3.2 project:

```
wp acorn vendor:publish --tag="woocommerce-template-views"
```

I am getting:

```
In Filesystem.php line 34:

  League\Flysystem\Filesystem::__construct(): Argument #1 ($adapter) must be of type League\Flysystem\AdapterInterface, League\Flysystem\Local\LocalFilesystemAdapter given, call
  ed in /[OMISSIS]/vendor/roots/acorn/src/Illuminate/Foundation/Console/VendorPublishCommand.php on line 278
```

**Comment by oxyc** [comment]
This isnt really sage-woocommerce related. It looks like your codebase resolves to league/flysystem [1.x branch](https://github.com/thephpleague/flysystem/blame/1.x/src/Filesystem.php#L35). Acorn v2 used this version but since v3 it's not. Which acorn version are you using?

Could also be some other WP plugin that bundles the package and takes precedence, I would grep the codebase for the package.
